fix: branching-check
Fix errors that were made in the creation of the workflow
fix: pr pattern matching


fix: branch-checking


fix: if statement


fix: my brain


learn bash


yikes

diff --git a/.github/actions/branch-check/action.yml b/.github/actions/branch-check/action.yml
--- a/.github/actions/branch-check/action.yml
+++ b/.github/actions/branch-check/action.yml
@@ -1,7 +1,7 @@
 name: Check PR branching
+description: Refuses PRs if the origin branch is not matching a pattern
 inputs:
   allowedBranches:
-    default: [ ]
     required: true
     description: branches that are allowed as origin of the PR
 
@@ -13,15 +13,18 @@ outputs:
 runs:
   using: "composite"
   steps:
-    - name: check constraint
-      run: export VALID_PR=[[ $GITHUB_HEAD_REF == @(${{ inputs.allowedBranches }}) ]]
-      shell: bash
     - name: set message
       id: messageGen
       run: |
-        export MSG="PRs to $GITHUB_BASE_REF need to come from one of theese branches: ${{input.allowedBranches}}"
-        echo "::set-output name=message::'$MSG'"
+        export MSG="PRs to \`$GITHUB_BASE_REF\` need to come from one of theese branches: \`${{inputs.allowedBranches}}\`"
+        echo "::set-output name=message::$MSG"
       shell: bash
     - name: fail on error
-      if: ${{env.VALID_PR}}
-      run: exit 1
+      shell: bash
+      run: |
+        if [[ "${{ github.head_ref }}" =~ ${{ inputs.allowedBranches }} ]];
+        then exit 0
+        else
+          echo "::error::$MSG"
+          exit 1
+        fi
